/* Generated by AN DISI Unibo */ 
package it.unibo.fireflyqueen

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Fireflyqueen ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var Timer = java.util.Random().nextLong(500L,1000L )
			   var TimeToSync = 10000	
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Hi I'm the qeen, my time is $Timer, waiting 10 sec...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", TimeToSync )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="handleSync",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("handleSync") { //this:State
					action { //it:State
						emit("sync", "time($Timer)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleSync", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="handleSync",cond=whenTimeout("local_tout_"+name+"_handleSync"))   
				}	 
			}
		}
} 
