/* Generated by AN DISI Unibo */ 
package it.unibo.creator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Creator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						  
								 clearlog("./logs/qakdemo26.log") 	//vedi src/main/resources/logback.xml
						CommUtils.outcyan("$name : trying to create fireflies")
						forward("start", "start(400)" ,"helper" ) 
						 logger.info(  "${currentState.stateName} Create actors 100 fireflys"  )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", 10000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="end",cond=whenTimeout("local_tout_"+name+"_s0"))   
					transition(edgeName="t01",targetState="buildFireflyActor",cond=whenDispatch("build"))
				}	 
				state("buildFireflyActor") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("build(X)"), Term.createTerm("build(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val arg = payloadArg(0)
												val num = arg.toInt()
								createActorDynamically("firefly", "_$num", false)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_buildFireflyActor", 
				 	 					  scope, context!!, "local_tout_"+name+"_buildFireflyActor", 10000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="end",cond=whenTimeout("local_tout_"+name+"_buildFireflyActor"))   
					transition(edgeName="t03",targetState="buildFireflyActor",cond=whenDispatch("build"))
				}	 
				state("end") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName} ends"  )  
						CommUtils.outmagenta("$name | SIMULATON ENDS")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
