/* Generated by AN DISI Unibo */ 
package it.unibo.robotsmartusage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotsmartusage ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				val StepTime = 345 
				val NLAP = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | starts ")
						 clearlog("./logs/robotsmart26usage.log") 			//vedi src/main/resources/logback.xml  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doplan", cond=doswitch() )
				}	 
				state("doplan") { //this:State
					action { //it:State
						 val Plan = "llllllllllllllllllll" 
						CommUtils.outblue("$name | doplan $Plan")
						request("doplan", "doplan($Plan,$StepTime)" ,"robotsmart" )  
						delay(4000) 
						emit("alarm", "alarm(X)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleReplyDone",cond=whenReply("doplandone"))
					transition(edgeName="t01",targetState="handleReplyFailed",cond=whenReply("doplanfailed"))
				}	 
				state("handleReplyDone") { //this:State
					action { //it:State
						CommUtils.outblue("$name | state plan Done")
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleReplyFailed") { //this:State
					action { //it:State
						CommUtils.outblue("$name | state Plan Failed")
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("doplanfailed(PLANTODO)"), Term.createTerm("doplanfailed(PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  
											   val toDo =  payloadArg(0)
								CommUtils.outblack("$name | $toDo")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
