/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var X = 0
				var Y = 0
			   var Timer = java.util.Random().nextLong(500L,1000L )
				var TimerUnsync = Timer
			   fun setCellCoords( )  {
		     		val coords = name.replace("firefly_","").split("_")   
		     		X  = coords[0].toInt()
		     		Y  = coords[1].toInt()        
		  		}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Hi I'm a firefly, I blink every $TimerUnsync ms")
						 setCellCoords( )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
				state("flash") { //this:State
					action { //it:State
						
						                Timer = TimerUnsync 
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t03",targetState="syncflash",cond=whenEvent("sync"))
				}	 
				state("syncflash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("args(X)"), Term.createTerm("args(Time)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                Timer = payloadArg(0).toLong()
								CommUtils.outcyan("$name | Timer updated to $Timer")
						}
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_syncflash", 
				 	 					  scope, context!!, "local_tout_"+name+"_syncflash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t04",targetState="syncflash",cond=whenTimeout("local_tout_"+name+"_syncflash"))   
					transition(edgeName="t05",targetState="flash",cond=whenEvent("unsync"))
				}	 
			}
		}
} 
