/* Generated by AN DISI Unibo */ 
package it.unibo.sonarsimulator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarsimulator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var DMIN = 100
				var Timer = java.util.Random().nextLong(600L,1000L)
				var TimerEvent1 = 10000L
				var TimerEvent2 = 10000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | sonar on")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleUnsync", cond=doswitch() )
				}	 
				state("handleUnsync") { //this:State
					action { //it:State
						CommUtils.outblue("$name | we are far form $DMIN meters")
						emit("unsync", "argu($Timer)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleUnsync", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleUnsync", TimerEvent1 )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="handleSync",cond=whenTimeout("local_tout_"+name+"_handleUnsync"))   
				}	 
				state("handleSync") { //this:State
					action { //it:State
						CommUtils.outblue("$name | ATTENCTION we are less than $DMIN meters")
						emit("sync", "args($Timer)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleSync", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleSync", TimerEvent2 )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="handleUnsync",cond=whenTimeout("local_tout_"+name+"_handleSync"))   
				}	 
			}
		}
} 
