/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		  
				var num		= 0
			  	val DT = (200L..2000L).random()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Hi I'm alive, I blink every $DT ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", DT )  //OCT2023
					}	 	 
					 transition(edgeName="t04",targetState="handleBlink",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("handleBlink") { //this:State
					action { //it:State
						 num ++  
						CommUtils.outyellow("$name | $num light on")
						delay(500) 
						CommUtils.outblack("$name | $num light off")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleBlink", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleBlink", DT )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="handleBlink",cond=whenTimeout("local_tout_"+name+"_handleBlink"))   
				}	 
			}
		}
} 
