/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		  
				var gridlen = 20
				var num		= 0
			  	val DT = (1000L..2000L).random()
			  	val id = name.substringAfterLast("_").toInt()
			  	var Y = id % gridlen 
			  	var X = id / gridlen
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Hi I'm alive, I blink every $DT ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleBlink", cond=doswitch() )
				}	 
				state("handleBlink") { //this:State
					action { //it:State
						 
									num ++ 
									var Timer = java.util.Random().nextLong(500L,1000L )  
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(Timer)
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleBlink", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleBlink", DT )  //OCT2023
					}	 	 
					 transition(edgeName="t04",targetState="handleBlink",cond=whenTimeout("local_tout_"+name+"_handleBlink"))   
				}	 
			}
		}
} 
