/* Generated by AN DISI Unibo */ 
package it.unibo.boundaryworker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Boundaryworker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 val MAX_TURNS = 4; var turns = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="walking", cond=doswitch() )
				}	 
				state("walking") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | going straight")
						request("step", "step(2500)" ,"robotactor" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="walking",cond=whenReply("stepdone"))
					transition(edgeName="t01",targetState="turning",cond=whenReply("stepfailed"))
				}	 
				state("turning") { //this:State
					action { //it:State
						 turns++  
						CommUtils.outyellow("$name | wall hit ($turns/$MAX_TURNS), turning left")
						forward("move", "move(l)" ,"robotactor" ) 
						if(  turns >= MAX_TURNS  
						 ){forward("move", "move(h)" ,"robotactor" ) 
						CommUtils.outred("$name | boundary walk complete after $turns turns")
						System.exit(0) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="walking", cond=doswitch() )
				}	 
			}
		}
} 
